### PR TITLE
Edits to VICTOR home page

### PR DESCRIPTION
**Pull request by volcanocyber**

### CODE REVIEW

**Review by sgibson91 — APPROVED** [review]

**Comment by colliand** [comment]
The logo image for Project VICTOR is not appearing on the [login page](https://victor.2i2c.cloud/hub/login?next=%2Fhub%2F). FYI @volcanocyber.

**Comment by damianavila** [comment]
I think the problem is described in this comment by @consideRatio: https://github.com/2i2c-org/infrastructure/pull/3067#issuecomment-1702930980.

**Comment by volcanocyber** [comment]
I don't fully follow. @damianavila Does the logo need to be local? Not too familiar with the Python templates.

**Comment by consideRatio** [comment]
@volcanocyber in https://github.com/2i2c-org/default-hub-homepage/pull/26 there was a change made to a file called `jupyterhub_config.py`, that jupyterhub config is never used when you visit https://victor.2i2c.cloud/ though. Instead, that config would only be used if you wanted to try how your login page would look locally.

What is needed is that the configuration in 2i2c-org/infrastructure is updated, specifically the config [here](https://github.com/2i2c-org/infrastructure/blob/7f00146d4cb22d067500c76a27dc406f01d1119b/config/clusters/victor/common.values.yaml#L20-L34).

Do you want us to update that config based on information from this PR, so that its reflected at https://victor.2i2c.cloud/?

```
        'org': {
            'name': 'VICTOR',
            'logo_url': 'https://i.imgur.com/D2vXQ5k.png',
            'url': 'https://victor.ldeo.columbia.edu',
        },
        'operated_by': {
            'name': '2i2c',
            'url': 'https://2i2c.org',
            'custom_html': '',
        },
        'funded_by': {
            'name': 'National Science Foundation',
            'url': 'https://people.climate.columbia.edu/projects/sponsor/National%20Science%20Foundation',
            'custom_html': 'Funding <i>Org</i>',
        },
        'designed_by': {
            'name': '2i2c',
            'url': 'https://2i2c.org',
            'custom_html': '',
        }
```

**Comment by consideRatio** [comment]
@volcanocyber I went ahead and updated the configuration that influences staging.victor.2i2c.cloud and victor.2i2c.cloud in https://github.com/2i2c-org/infrastructure/pull/3133 feeling confident this was desired and about to end my work day.

**Comment by consideRatio** [comment]
image

**Pull request merged**
